### ISSUE TITLE
Hi, getting smartapp adding error

### ISSUE THREAD

**Issue by mugunthan74** [bdwilson/SmartThings-GeoHopper-Presence#2]
startup failed: script_app_metadata_03875bc5_e483_4087_8f04_965e0b6cb905: 60: expecting anything but ''\n''; got it anyway @ line 60, column 72. me}, attribute ${it.name}, ID: ^ 1 error

**Comment by bdwilson** [comment]
Try again with the latest version. There was a line wrapping issue.  Sorry for that, and thanks for letting me know.

**Comment by mugunthan74** [comment]
Hi, Thanks for fixing the code, I have done everything 100% to your list.

getting the following error in Smartthings log and geohopper not updating the Smartthings as well :(

a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:37:40: error physicalgraph.app.exception.SmartAppException: Device not found
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:37:40: debug Error: device (null) not found
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:37:40: debug event: LocationExit device: null location: Geohopper
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:37:40: debug update, request: params: [access_token:5ad6b9ca-0faf-4391-be56-bf0e0fb5c9db, appId:a09f522a-7e90-44e3-9e08-aa98a06a2e07, param1:location, action:[GET:executeSmartAppGet, POST:executeSmartAppPost, PUT:executeSmartAppPut, DELETE:executeSmartAppDelete, OPTIONS:executeSmartAppOptions], controller:smartAppApi], data, [sender:mukun74@gmail.com, time:2017-12-19 01:37:40 +0000, location:Geohopper, event:LocationExit], devices: [01949b44-6fa1-45af-ba80-3ba4b40a36d0], [GeoHopper]
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:36:22: error physicalgraph.app.exception.SmartAppException: Device not found
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:36:22: debug Error: device (null) not found
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:36:22: debug event: LocationEnter device: null location: Geohopper
a09f522a-7e90-44e3-9e08-aa98a06a2e07  01:36:22: debug update, request: params: [access_token:5ad6b9ca-0faf-4391-be56-bf0e0fb5c9db, appId:a09f522a-7e90-44e3-9e08-aa98a06a2e07, param1:location, action:[GET:executeSmartAppGet, POST:executeSmartAppPost, PUT:executeSmartAppPut, DELETE:executeSmartAppDelete, OPTIONS:executeSmartAppOptions], controller:smartAppApi], data, [sender:mukun74@gmail.com, time:2017-12-19 01:36:22 +0000, location:Geohopper, event:LocationEnter], devices: [01949b44-6fa1-45af-ba80-3ba4b40a36d0], [GeoHopper]

**Comment by bdwilson** [comment]
Your virtual device name is null (as received from Geohopper).  This has to be the name of the virtual device you've created.  For instance, my location in GeoHopper is called "Virtual AC Presence" and that's also the name of the Virtual Device in SmartThings.

**Comment by mugunthan74** [comment]
![geohooper screen shot](https://user-images.githubusercontent.com/33517466/34272285-98e2f4d8-e687-11e7-9afd-675086d7e3a1.jpg)

**Comment by mugunthan74** [comment]
![img_1724](https://user-images.githubusercontent.com/33517466/34273543-baad492e-e68c-11e7-855e-b276951ecbe5.PNG)

**Comment by mugunthan74** [comment]
I have named everything GeoHopper.

**Comment by bdwilson** [comment]
It appears location:Geohopper so maybe try renaming your device to be Geohopper not GeoHopper and see if that works.

**Comment by mugunthan74** [comment]
Yep it works, I have deleted it and added it again.
Thank you so much 👍🏼👌
